# hdn-layout
keycode  10 = nine
    shift keycode  10 = less
keycode  11 = zero
    shift keycode  11 = greater
keycode  12 = equal
    shift keycode  12 = underscore
keycode  13 = backslash
    shift keycode  13 = bar
#
keycode  16 = w
keycode  17 = f
keycode  18 = m
keycode  19 = p
keycode  20 = v
keycode  21 = slash
    shift keycode  21 = asterisk
keycode  22 = period
    shift keycode  22 = colon
keycode  23 = q
keycode  24 = quotedbl
    shift keycode  24 = bracketleft
keycode  25 = apostrophe
    shift keycode  25 = bracketright
keycode  26 = z
keycode  27 = parenleft
    shift keycode  27 = braceleft
#
keycode  30 = r
keycode  31 = s
keycode  32 = n
keycode  33 = t
keycode  34 = g
keycode  35 = comma
    shift keycode  35 = semicolon  
keycode  36 = a
keycode  37 = e
keycode  38 = i
keycode  39 = h
keycode  40 = j
keycode  43 = parenright
    shift keycode  43 = braceright
#
keycode  86 = question
    shift keycode  86 = bar
keycode  44 = x
keycode  45 = c
keycode  46 = l
keycode  47 = d
keycode  48 = b
keycode  49 = hyphen
keycode  50 = u
keycode  51 = o
keycode  52 = y
keycode  53 = k
#
include "compose"
