# hdn-layout
keycode  16 = w
keycode  17 = f
keycode  18 = m
keycode  19 = p
keycode  20 = v
keycode  21 = slash
keycode  22 = period
keycode  23 = q
keycode  24 = apostrophe
keycode  25 = quotedbl
#
keycode  30 = r
keycode  31 = s
keycode  32 = n
keycode  33 = t
keycode  34 = g
keycode  35 = comma
keycode  36 = a
keycode  37 = e
keycode  38 = i
#
keycode  44 = x
keycode  45 = c
keycode  46 = l
keycode  47 = d
keycode  48 = b
keycode  49 = hyphen
keycode  50 = u
keycode  51 = o
keycode  52 = y
keycode  53 = k
#
include "compose"
